name: SQL File Change Workflow

on:
  push:
    paths:
      - '*.sql'      
      - '**/*.sql' 

jobs:
  sql_change:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install sqldif
        run: |
          go install github.com/lll-lll-lll-lll/sqdif@v0.2.5
          echo "${HOME}/go/bin" >> $GITHUB_PATH
      
      - name: sqldif version check
        run: |
          sqdif --version

      - name: List changed SQL files
        id: list_sql_files
        run: |
          git diff --name-only HEAD^ HEAD | grep '\.sql$' > changed_sql_files.txt
      
      - name: Show changed SQL files
        run: |
          echo "Changed SQL files:"
          cat changed_sql_files.txt
