name: SQL File Change Workflow

on:
  push:
    paths:
      - '*.sql'      
      - '**/*.sql' 

jobs:
  sql_change:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install sqldif
        run: |
          go install github.com/lll-lll-lll-lll/sqdif@v0.2.5
          echo "${HOME}/go/bin" >> $GITHUB_PATH
      
      - name: sqldif version check
        run: |
          sqdif --version

      - name: List changed SQL files
        id: list_sql_files
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.sql$' || true
      
      - name: Execute SQL files
        run: |
          for file in $(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.sql$'); do
            echo "Executing $file"
            # Replace the following line with the actual command to execute your SQL files
            # For example, if using MySQL:
            # mysql -u your_username -p your_password your_database < $file
          done